services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: admin_dashboard
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"  # ⬅️ CHANGE ICI : 3307 à l'extérieur, 3306 à l'intérieur
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: